#!/bin/sh
#
# $Id: runtest,v 1.1 2001-11-19 01:37:25 gnb Exp $
#
CANT="${CANT:-../../src/cant} --globals-file globals.xml"

TMP=cant$$.stderr
trap "/bin/rm -f $TMP" 0

failed ()
{
    echo "FAILED"
    exit 1
}

compile_test ()
{
    VALUE="$1"
    EXPECTED="$2"
    
    echo "================================================================"
    echo "arg file test, value=$VALUE"
    
    /bin/rm -rf *.o foo
    $CANT all -Dtest009.abspath="$VALUE" --verbose >$TMP 2>&1 || failed
    cat $TMP
    
    test -x foo || failed
    grep "$EXPECTED" $TMP >/dev/null || failed
}


#set -x

compile_test no "\[compile\] gcc.* a.c"
compile_test yes "\[compile\] gcc.*/test/test009/a.c"


