#!/bin/sh
#
# $Id: runtest,v 1.2 2001-11-21 09:35:28 gnb Exp $
#

. ../testfunctions.sh

compile_test ()
{
    VALUE="$1"
    EXPECTED="$2"
    
    start_test "arg file"
    
    /bin/rm -rf *.o foo
    cant all -D"test009.abspath=$VALUE" --verbose
    
    check_file_executable foo
    check_output_re "$EXPECTED"
}

compile_test no "\[compile\] gcc.* a.c"
compile_test yes "\[compile\] gcc.*/test/test009/a.c"


