#!/bin/sh
#
# $Id: runtest,v 1.4 2002-04-12 13:08:08 gnb Exp $
#

. ../testfunctions.sh

parse_test ()
{
    local VALUE="$1"
    local EXPECTED="$2"
    
    start_test "parse error"
    
    cant_status -buildfile build-$VALUE.xml null
    case "$EXPECTED" in
    yes)
    	check_status yes
	;;
    no)
    	check_status no
	;;
    *)
    	check_status no
	check_output_re "ERROR:.*$EXPECTED"
	;;
    esac
}

parse_test ok yes
parse_test xml-format "invalid element name"
parse_test project-default "Required attribute \"default\""
parse_test project-unex-child "Element \"bastard\" unexpected"
parse_test duplicate-target "Target.*already defined"
parse_test missing-dep-target "depended on but never defined"
parse_test unknown-task "Unknown task"
parse_test missing-end-tag "ending tag mismatch"
parse_test unknown-mapper "Unknown mapper type"
parse_test glob-mapper-from "Bad \"from\" expression"
parse_test glob-mapper-to "Bad \"to\" expression"
parse_test regexp-mapper "Unmatched \["

