#!/bin/sh
#
# $Id: runtest,v 1.1 2001-11-18 11:17:42 gnb Exp $
#
CANT="${CANT:-../../src/cant} --globals-file globals.xml"

TMP=cant$$.stderr
trap "/bin/rm -f $TMP" 0

failed ()
{
    echo "FAILED"
    exit 1
}

parse_test ()
{
    local VALUE="$1"
    local EXPECTED="$2"
    local STATUS
    
    echo "================================================================"
    echo "parse error test, value=$VALUE"
    
    /bin/rm -f $TMP
    $CANT -buildfile build-$VALUE.xml null >$TMP 2>&1
    STATUS=$?
    cat $TMP
    case "$EXPECTED" in
    yes)
    	test $STATUS = 0 || failed
	;;
    no)
    	test $STATUS != 0 || failed
	;;
    *)
    	test $STATUS != 0 || failed
    	grep "ERROR:.*$EXPECTED" $TMP >/dev/null || failed
	;;
    esac
}

#set -x

parse_test ok yes
parse_test xml-format "invalid element name"
parse_test project-default "Required attribute \"default\""
parse_test project-unex-child "Element \"bastard\" unexpected"
parse_test duplicate-target "Target.*already defined"
parse_test missing-dep-target "depended on but never defined"
parse_test unknown-task "Unknown task"
parse_test missing-end-tag "ending tag mismatch"



