#!/bin/sh
#
# $Id: runtest,v 1.2 2001-11-21 09:35:28 gnb Exp $
#

. ../testfunctions.sh

echo_test ()
{
    VALUE="$1"
    
    start_test "echo test"
    cant test-"$VALUE"
}

echo_test messages
check_output_file stdout.expected


/bin/rm -f wfile afile
echo_test files

check_file_exists wfile
check_file_hex wfile " 46 6f 6f 0a"

check_file_exists afile
check_file_hex afile " 42 61 72 42 61 7a 0a"
