#!/bin/sh
#
# $Id: runtest,v 1.3 2001-11-21 09:35:28 gnb Exp $
#

. ../testfunctions.sh

arg_test ()
{
    VALUE="$1"
    EXPECTED="$2"
    
    start_test "arg inclusion"
    
    /bin/rm -rf *.o foo
    cant all -Ddebug="$VALUE"
    
    check_file_executable foo
    
    vmessage "Checking whether foo is built with debugging"
    RESULT=`objdump --stabs foo |\
    	awk '$2 == "FUN" && $7 ~ /^main:/{res=1} END{print (res?"yes":"no")}'`
    test "$EXPECTED" = "$RESULT" || failed
}


matchprop_test ()
{
    VALUE="$1"
    EXPECTED="$2"
    
    start_test "match property"
    
    /bin/rm -rf *.o foo
    cant all -Dmatchprop="$VALUE"
    
    check_file_executable foo

    vmessage "Checking foo output"
    ./foo | grep "^${EXPECTED} b() called\$" || failed
}


boolprop_test ()
{
    VALUE="$1"
    EXPECTED="$2"
    
    start_test "bool property"
    
    /bin/rm -rf my-bindir
    cant install -Dboolprop="$VALUE"
    
    case "$EXPECTED" in
    bar)
	check_file_exists my-bindir/bar
	check_file_notexists my-bindir/baz
	;;
    baz)
	check_file_notexists my-bindir/bar
	check_file_exists my-bindir/baz
	;;
    esac
}

/bin/rm -rf foo *.o my-bindir

arg_test "" no
arg_test "anythingelse" yes

arg_test "yes" yes
arg_test "true" yes
arg_test "1" yes
arg_test "on" yes

arg_test "no" no
arg_test "false" no
arg_test "0" no
arg_test "off" no

matchprop_test "br" bar
matchprop_test "bar" bar
matchprop_test "baaar" bar
matchprop_test "baAar" bar
matchprop_test "" baz
matchprop_test "baz" baz
matchprop_test "anythingelse" baz

boolprop_test "" baz
boolprop_test "anythingelse" bar

boolprop_test "true" bar
boolprop_test "TRUE" bar
boolprop_test "True" bar
boolprop_test "on" bar
boolprop_test "oN" bar
boolprop_test "1" bar
boolprop_test "yes" bar
boolprop_test "YES" bar

boolprop_test "false" baz
boolprop_test "FALSE" baz
boolprop_test "False" baz
boolprop_test "off" baz
boolprop_test "oFF" baz
boolprop_test "0" baz
boolprop_test "no" baz
boolprop_test "NO" baz

